# This section is considered when running `cargo deny check advisories`
# More documentation for the advisories section can be found here:
# https://embarkstudios.github.io/cargo-deny/checks/advisories/cfg.html
[advisories]
# The path where the advisory databases are cloned/fetched into
# db-path = "$CARGO_HOME/advisory-dbs"
# The url(s) of the advisory databases to use
# db-urls = ["https://github.com/rustsec/advisory-db"]
# A list of advisory IDs to ignore. Note that ignored advisories will still
# output a note when they are encountered.
ignore = [
  # "RUSTSEC-0000-0000",
  # { id = "RUSTSEC-0000-0000", reason = "you can specify a reason the advisory is ignored" },
  # "a-crate-that-is-yanked@0.1.1", # you can also ignore yanked crate versions if you wish
  # { crate = "a-crate-that-is-yanked@0.1.1", reason = "you can specify why you are ignoring the yanked crate" },
  { id = "RUSTSEC-2024-0370", reason = "Not updated upstream yet see https://github.com/shuttle-hq/shuttle/issues/1873" },
]
