name: Shuttle Deploy

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-shuttle-deploy
  cancel-in-progress: true

on:
  schedule:
    - cron: '25 05 20 * *' # 01:25 GMT-4
  push:
    branches:
      - main
      

env:
  CARGO_TERM_COLOR: always
      
jobs:
  # https://docs.github.com/en/actions/sharing-automations/reusing-workflows#calling-a-reusable-workflow
  run_tests:
    uses: ./.github/workflows/general.yml
  deploy:
    runs-on: ubuntu-latest
    needs: run_tests
    steps:
      - uses: shuttle-hq/deploy-action@v2
        with:
          shuttle-api-key: ${{ secrets.SHUTTLE_API_KEY }}
          project-id: proj_01JHHNVETW1ZV6SKYDYKDX046T